version: '3'
services:
  property-listing:
    container_name: property-listing
    build: .
    ports:
     - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_DATABASE: property-listing
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - '27017:27017'
