version: '3'
services:
  property-listing:
    container_name: property-listing
    build: .
    ports:
     - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongodb
    image: aashreys/mongo-auth:latest
    volumes:
      - ../data/db:/data/db
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=admin
      - MONGODB_ADMIN_PASS=admin123
      - MONGODB_APPLICATION_DATABASE=property-listing
      - MONGODB_APPLICATION_USER=admin
      - MONGODB_APPLICATION_PASS=admin123
    ports:
      - '27017:27017'
