version: '3'
services:
  property-listing:
    container_name: property-listing
    build: .
    ports:
     - "3000:3000"
    depends_on:
      - mongo
  fix-mongo-permissions:
    image: 'bitnami/mongodb:latest'
    user: root
    command: chown -R 1001:1001 /bitnami
    volumes:
      - ../data/db:/bitnami
  mongo:
    container_name: mongodb
    image: bitnami/mongodb:latest
    volumes:
      - ../data/db:/bitnami
    environment:
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=admin123
      - MONGODB_DATABASE=property-listing
    ports:
      - '27017:27017'
    depends_on:
      - fix-mongo-permissions
